### ISSUE TITLE
Imported events into Events Manager not appearing in admin

### ISSUE THREAD

**Issue by EddyRespondek** [xylusthemes/import-eventbrite-events#2]
When importing events into Events Manager plugin they are hidden from the admin backend. The only way to edit the event is to search for the event post ID and manually enter the url. 

Looking at the code I narrowed it down to a missing post meta field. 

Adding the following lines to /includes/class-import-eventbrite-events-em.php after line 160 fixes the issue - 

```
update_post_meta( $inserted_event_id, '_event_start_local', date( 'Y-m-d H:i:s', $start_time ) );
update_post_meta( $inserted_event_id, '_event_end_local', date( 'Y-m-d H:i:s', $end_time ) );
```

This works for me however, I'm not sure the date values I'm adding are correct (should they be adjusted for local time?)

**Comment by iamdharmesh** [comment]
Hello @EddyRespondek, 

Thanks for report issue. The issue is happen because of recent update in Events Manager 5.9. They have added new post meta fields and new columns in custom table of events for add support of timezone. 

We will fix it soon and release hot fix release of that soon. so for now you can update plugin code like we updated here ( https://github.com/xylusthemes/import-facebook-events/commit/44a6cd8b2096837129311496423130d2c4b2353d )

Thanks,
Dharmesh

**Comment by iamdharmesh** [comment]
Hello @EddyRespondek,

We have added support for Events Manager 5.9 in version 1.4.1. you can download it from wp.org.

Thanks,
Dharmesh
